resolver: lts-9.21

# User packages to be built.
# Various formats can be used as shown in the example below.
#
# packages:
# - some-directory
# - https://example.com/foo/bar/baz-0.0.2.tar.gz
# - location:
#    git: https://github.com/commercialhaskell/stack.git
#    commit: e7b331f14bcffb8367cd58fbfc8b40ec7642100a
# - location: https://github.com/commercialhaskell/stack/commit/e7b331f14bcffb8367cd58fbfc8b40ec7642100a
#  subdirs:
#  - auto-update
#  - wai
packages:
- reflex-eda-common
- reflex-eda-gtk

allow-newer: true

# Dependency packages to be pulled from upstream that are not in the resolver
# using the same syntax as the packages field.
# (e.g., acme-missiles-0.3)
extra-deps:
- git: https://github.com/reflex-frp/reflex.git
  commit: "2121f9990ce2daa2d7e8133317b4701bdd795f22"
- git: https://github.com/reflex-frp/reflex-dom.git
  commit: "8bde2d72193369c92a995820ca1f56690d3c8ec3"
  subdirs:
  - reflex-dom-core
  - reflex-dom
- git: https://github.com/reflex-frp/reflex-dom-contrib.git
  commit: "3efa8e4fa35161ea967252106ef7177a8360485b"
# recommended by stack
- dependent-sum-template-0.0.0.6
- ghcjs-dom-0.9.2.0
# - ghcjs-dom-jsffi-0.9.2.0
- ghcjs-dom-jsaddle-0.9.2.0
- jsaddle-0.9.5.0
- jsaddle-dom-0.9.2.0
- jsaddle-webkit2gtk-0.9.4.0
- gi-webkit2-4.0.15
- webkit2gtk3-javascriptcore-0.14.2.1
- prim-uniq-0.1.0.1
- ref-tf-0.4.0.1
- zenc-0.1.1
- monoidal-containers-0.4.0.0



# Override default flag values for local packages and extra-deps
# flags: {}

# Extra package databases containing global packages
# extra-package-dbs: []

# Control whether we use the GHC we find on the path
# system-ghc: true
#
# Require a specific version of stack, using version ranges
# require-stack-version: -any # Default
# require-stack-version: ">=1.7"
#
# Override the architecture used by stack, especially useful on Windows
# arch: i386
# arch: x86_64
#
# Extra directories used by stack for building
# extra-include-dirs: [/path/to/dir]
# extra-lib-dirs: [/path/to/dir]
#
# Allow a newer minor version of GHC than the snapshot specifies
# compiler-check: newer-minor
